#!/usr/bin/env python
# Copyright (c) 2016, AB Uobis
# All rights reserved.

from xac import db
from xac import models

db.drop_all()
db.create_all()

assets_entry =  models.Elements(name = 'Assets')
db.session.add(assets_entry)
liabilities_entry =  models.Elements(name = 'Liabilities')
db.session.add(liabilities_entry)
equity_entry =  models.Elements(name = 'Equity')
db.session.add(equity_entry)
db.session.commit()

assets_entry =  models.Classifications(name = 'Current Assets', parent = 'Assets')
db.session.add(assets_entry)
liabilities_entry =  models.Classifications(name = 'Current Liabilities', parent = 'Liabilities')
db.session.add(liabilities_entry)
equity_entry =  models.Classifications(name = "Stockholders' Equity", parent = 'Equity')
db.session.add(equity_entry)
revenues_entry =  models.Classifications(name = 'Revenues', parent = 'Equity')
db.session.add(revenues_entry)
expenses_entry =  models.Classifications(name = 'Expenses', parent = 'Equity')
db.session.add(expenses_entry)
gains_entry =  models.Classifications(name = 'Gains', parent = 'Equity')
db.session.add(gains_entry)
losses_entry =  models.Classifications(name = 'Losses', parent = 'Equity')
db.session.add(losses_entry)
db.session.commit()

assets_entry =  models.Accounts(name = 'Bitcoins', parent = 'Current Assets')
db.session.add(assets_entry)
liabilities_entry =  models.Accounts(name = 'Accounts Payable', parent = 'Current Liabilities')
db.session.add(liabilities_entry)
equity_entry =  models.Accounts(name = 'Common Stock', parent = "Stockholders' Equity")
db.session.add(equity_entry)
equity_entry =  models.Accounts(name = 'Retained Earnings', parent = "Stockholders' Equity")
db.session.add(equity_entry)
revenues_entry =  models.Accounts(name = 'Service Revenues', parent = 'Revenues')
db.session.add(revenues_entry)
revenues_entry =  models.Accounts(name = 'Revenues', parent = 'Revenues')
db.session.add(revenues_entry)
expenses_entry =  models.Accounts(name = 'Expenses', parent = 'Expenses')
db.session.add(expenses_entry)
expenses_entry =  models.Accounts(name = 'Rent Expense', parent = 'Expenses')
db.session.add(expenses_entry)
gains_entry =  models.Accounts(name = 'Asset Sale Gains', parent = 'Gains')
db.session.add(gains_entry)
losses_entry =  models.Accounts(name = 'Asset Sale Losses', parent = 'Losses')
db.session.add(losses_entry)
db.session.commit()

assets_entry =  models.Subaccounts(name = 'Coinbase', parent = 'Bitcoins')
db.session.add(assets_entry)
assets_entry =  models.Subaccounts(name = 'MultiBit', parent = 'Bitcoins')
db.session.add(assets_entry)
assets_entry =  models.Subaccounts(name = 'Bitcoin Core', parent = 'Bitcoins')
db.session.add(assets_entry)
assets_entry =  models.Subaccounts(name = 'Electrum', parent = 'Bitcoins')
db.session.add(assets_entry)
assets_entry =  models.Subaccounts(name = 'Armory', parent = 'Bitcoins')
db.session.add(assets_entry)
liabilities_entry =  models.Subaccounts(name = 'Accounts Payable', parent = 'Accounts Payable')
db.session.add(liabilities_entry)
equity_entry =  models.Subaccounts(name = 'Common Stock', parent = "Common Stock")
db.session.add(equity_entry)
equity_entry =  models.Subaccounts(name = 'Retained Earnings', parent = "Retained Earnings")
db.session.add(equity_entry)
revenues_entry =  models.Subaccounts(name = 'Revenues', parent = 'Revenues')
db.session.add(revenues_entry)
revenues_entry =  models.Subaccounts(name = 'Salary', parent = 'Service Revenues')
db.session.add(revenues_entry)
expenses_entry =  models.Subaccounts(name = 'Rent Expense', parent = 'Rent Expense')
db.session.add(expenses_entry)
expenses_entry =  models.Subaccounts(name = 'Expenses', parent = 'Expenses')
db.session.add(expenses_entry)
gains_entry =  models.Subaccounts(name = 'Gains from the Sale of Bitcoins', parent = 'Asset Sale Gains')
db.session.add(gains_entry)
losses_entry =  models.Subaccounts(name = 'Losses from the Sale of Bitcoins', parent = 'Asset Sale Losses')
db.session.add(losses_entry)
db.session.commit()
